apiVersion: v1
kind: Service
metadata:
  name: free5gc-test-svc
spec:
  selector:
    app: free5gc-test
  clusterIP: None # 10.96.100.50
  ports:
    - name: sctp
      protocol: SCTP
      port: 9487
    - name: udp
      protocol: UDP
      port: 2152
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-test-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-test
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-test
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-test:stage3.0.4
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "ip addr add 60.60.0.1 dev lo && ip link set dev lo up && sleep 3650d"]
