apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: free5gc-udm-dr
spec:
  host: free5gc-udm-svc
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        http2MaxRequest: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 3s
      maxEjectionPercent: 100
