apiVersion: v1
kind: Service
metadata:
  name: free5gc-amf-svc
spec:
  selector:
    app: free5gc-amf
  ports:
    - name: sbi
      protocol: TCP
      port: 29518
    - name: sctp
      protocol: SCTP
      port: 38412
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-amf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-amf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/free5gc-control-plane:stage3.0.4
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/amf"]
        volumeMounts:
        - name: amfcfg
          mountPath: /go/src/free5gc/config/amfcfg.conf
          subPath: amfcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: amfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: amfcfg.conf
            path: amfcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
      
