kind: Service
apiVersion: v1
metadata:
  name: free5gc-webui-svc
spec:
  selector:
    app: free5gc-webui
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 31111
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-webui-configmap
data:
  webuicfg.yaml: |
    info:
      version: 1.0.0
      description: WebUI initial local configuration

    configuration:
      mongodb:                                # the mongodb connected by this webui
        name: free5gc                         # name of the mongodb
        url: mongodb://mongodb-svc:27017      # a valid URL of the mongodb

    # the kind of log output
    # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
    # ReportCaller: enable the caller report or not, value: true or false
    logger:
      WEBUI:
        debugLevel: info
        ReportCaller: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-webui-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:
      - name: free5gc-webui
        command: ["/bin/bash", "-c"]
        args: ["./webconsole/bin/webconsole"]
        image: free5gmano/free5gc-webui:stage3.2.1-amd64
        env:
        - name: GIN_MODE
          value: debug # debug | release
        volumeMounts:
        - name: webuicfg
          mountPath: /free5gc/config/webuicfg.yaml
          subPath: webuicfg.yaml
      volumes:
      - name: webuicfg
        configMap:
          name: free5gc-webui-configmap
          items: 
          - key: webuicfg.yaml
            path: webuicfg.yaml
