kind: ConfigMap
metadata:
  name: open5gs-configmap
apiVersion: v1
data:
  amf.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/amf.log
    amf:
        sbi:
          - addr: 192.168.2.7
            port: 7777
        ngap:
          - addr: 192.168.2.7
        guami:
          - plmn_id:
              mcc: 460
              mnc: 99
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: 460
              mnc: 99
            tac: 1
        plmn_support:
          - plmn_id:
              mcc: 460
              mnc: 99
            s_nssai:
              - sst: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf0

    nrf:
        sbi:
          - addr:
              - 192.168.2.12
            port: 7777

    parameter:

    max:

    pool:

    time:

  ausf.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/ausf.log
    ausf:
        sbi:
          - addr: 192.168.2.13
            port: 7777

    nrf:
        sbi:
          - addr:
              - 192.168.2.12
            port: 7777

    parameter:

    max:

    pool:

    time:

  hss.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs

    logger:
        file: /open5gs/install/var/log/open5gs/hss.log

    hss:
        freeDiameter: /open5gs/install/etc/freeDiameter/hss.conf

    parameter:

    max:

    pool:
  
  mme.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/mme.log

    mme:
        freeDiameter: /open5gs/install/etc/freeDiameter/mme.conf
        s1ap:
          - addr: 192.168.2.4
        gtpc:
          - addr: 192.168.2.4
        gummei: 
          plmn_id:
            mcc: 460
            mnc: 99
          mme_gid: 2
          mme_code: 1
        tai:
          plmn_id:
            mcc: 460
            mnc: 99
          tac: 1
        security:
            integrity_order : [ EIA2, EIA1, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
        network_name:
            full: Open5GS
        mme_name: open5gs-mme0

    sgwc:
        gtpc:
          - addr: 192.168.2.5

    smf:
        gtpc:
          - addr:
            - 192.168.2.6

    parameter:

    max:

    pool:

    sctp:

    time:
  
  nrf.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs

    logger:
        file: /open5gs/install/var/log/open5gs/nrf.log

    nrf:
        sbi:
          addr:
            - 192.168.2.12
          port: 7777

    parameter:

    max:

    pool:

    time:
  
  pcf.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs

    logger:
        file: /open5gs/install/var/log/open5gs/pcf.log
    pcf:
        sbi:
          - addr: 192.168.2.15
            port: 7777

    nrf:
        sbi:
          - addr:
            - 192.168.2.12
            port: 7777

    parameter:

    max:

    pool:

    time:
  
  pcrf.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs

    logger:
        file: /open5gs/install/var/log/open5gs/pcrf.log

    pcrf:
        freeDiameter: /open5gs/install/etc/freeDiameter/pcrf.conf

    parameter:

    max:

    pool:
  
  sgwc.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/sgwc.log

    sgwc:
        gtpc:
          - addr: 192.168.2.5
        pfcp:
          - addr: 192.168.2.5

    sgwu:
        pfcp:
          - addr: 192.168.2.8

    parameter:

    max:

    pool:

    time:
  
  sgwu.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/sgwu.log

    sgwu:
        gtpu:
          - addr: 192.168.2.8
        pfcp:
          - addr: 192.168.2.8

    sgwc:

    parameter:

    max:

    pool:

    time:
  
  smf.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/smf.log
    smf:
        sbi:
          - addr: 192.168.2.6
            port: 7777
        gtpc:
          - addr: 192.168.2.6
        pfcp:
          - addr: 192.168.2.6
        pdn:
          - addr: 10.45.0.1/16
          - addr: cafe::1/64
        dns:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
        mtu: 1400
        freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf

    nrf:
        sbi:
          - addr:
            - 192.168.2.12
            port: 7777

    upf:
        pfcp:
          - addr: 192.168.2.9

    parameter:

    max:

    pool:

    time:
  
  udm.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/udm.log
    udm:
        sbi:
          - addr: 192.168.2.14
            port: 7777

    nrf:
        sbi:
          - addr:
            - 192.168.2.12
            port: 7777

    parameter:

    max:

    pool:

    time:
  
  udr.yaml: |
    db_uri: mongodb://mongodb-svc/open5gs

    logger:
        file: /open5gs/install/var/log/open5gs/udr.log
    udr:
        sbi:
          - addr: 192.168.2.16
            port: 7777

    nrf:
        sbi:
          - addr:
            - 192.168.2.12
            port: 7777

    parameter:

    max:

    pool:

    time:
  
  upf.yaml: |
    logger:
        file: /open5gs/install/var/log/open5gs/upf.log

    upf:
        pfcp:
          - addr: 192.168.2.9
        gtpu:
          - addr: 192.168.2.9
        pdn:
          - addr: 10.45.0.1/16
          - addr: cafe::1/64

    smf:

    parameter:

    max:

    pool:

    time:
