apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-upf-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-upf
    spec:
      containers:      
      - name: open5gs-upf-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "/open5gs/install/setup-uptun.sh && /open5gs/install/bin/open5gs-upfd"]
        volumeMounts:
          - mountPath: /dev/net/tun
            name: tun-volume
          - name: open5gs-upfcfg
            mountPath: /open5gs/install/etc/open5gs/upf.yaml
            subPath: upf.yaml
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.168.2.9/23"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: open5gs-upfcfg
        configMap:
          name: open5gs-configmap
          items:
          - key: upf.yaml
            path: upf.yaml
