apiVersion: v1
kind: Service
metadata:
  name: free5gc-anchor2-upf-svc
spec:
  selector:
    app: free5gc-anchor2-upf
  clusterIP: None # 10.96.100.10
  ports:
    - name: sbi
      port: 29518
      protocol: TCP
    - name: gtp
      protocol: UDP
      port: 2152
    - name: pfcp
      protocol: UDP
      port: 8805
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-anchor2-upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-anchor2-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-anchor2-upf
    spec:
      containers:      
      - name: free5gc-upf-container
        image: free5gmano/free5gc-user-plane:stage3.0.4
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        # args: ["-c", "ip addr add 60.60.0.100 dev lo && ip link set dev lo up && ./bin/free5gc-upfd"]
        args: ["-c", "sleep 10s && ./bin/free5gc-upfd"]
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-volume
        - name: upfcfg
          mountPath: /go/src/free5gc/src/upf/build/config/upfcfg.yaml
          subPath: anchor2-upfcfg.yaml
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: upfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: anchor2-upfcfg.yaml
            path: anchor2-upfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
