apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-upf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-upf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-upf
    spec:
      containers:      
      - name: free5gc-upf-container
        image: free5gmano/free5gc-user-plane
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args: ["-c", "./bin/free5gc-upfd && ip addr add 60.60.0.100/24 dev lo"]
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-volume
        - name: upfcfg
          mountPath: /go/src/free5gc/src/upf/build/config/upfcfg.yaml
          subPath: upfcfg.yaml
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.168.2.10/23", "-g=192.168.3.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: upfcfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: upfcfg.yaml
            path: upfcfg.yaml
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
