apiVersion: v1
data:
  free5gc.conf: |
    db_uri: mongodb://mongodb-svc/free5gc

    logger:
        file: /root/free5gc/install/var/log/free5gc/free5gc.log
        trace: 
            app: 1
            s1ap: 1
            nas: 1
            diameter: 1
            gtp: 1
            pfcp: 1
            sbi: 1

    # 
    # parameter:
    #
    #  o Number of output streams per SCTP associations.
    #      sctp_streams: 30
    #
    #  o Disable use of IPv4 addresses (only IPv6)
    #      no_ipv4: true
    #
    #  o Disable use of IPv6 addresses (only IPv4)
    #      no_ipv6: true
    #
    #  o Prefer IPv4 instead of IPv6 for estabishing new GTP connections.
    #      prefer_ipv4: true
    #
    #  o Enable Multicast traffic to the UE
    #      multicast: true
    #
    #  o Disable Stateless Address Autoconfiguration for IPv6
    #      no_slaac: true
    #
    #
    parameter:
        no_ipv6: true

    amf:
        freeDiameter: amf.conf

    #
    #  <S1AP Server>>
    #
    #  o S1AP Server(all address avaiable)
    #    s1ap:
    #
    #  o S1AP Server(0.0.0.0:36412)
    #    s1ap:
    #      addr: 0.0.0.0
    #
    #  o S1AP Server(127.0.0.1:36412, [::1]:36412)
    #    s1ap:
    #      - addr: 127.0.0.1
    #      - addr: ::1

    #  o S1AP Server(different port)
    #    s1ap:
    #      - addr: 127.0.0.1
    #        port: 36413
    #
    #  o S1AP Server(address avaiable in `eth0` interface)
    #    s1ap:
    #      dev: eth0
    #
        s1ap:
          addr: 192.168.2.2

    #
    #  <GUMMEI>
    #
    #  o Multiple GUMMEI
    #    gummei: 
    #      - plmn_id:
    #          mcc: 001
    #          mnc: 01
    #        mme_gid: 2
    #        mme_code: 1
    #      - plmn_id:
    #          - mcc: 002
    #            mnc: 02
    #          - mcc: 003
    #            mnc: 03
    #        mme_gid: [3, 4]
    #        mme_code:
    #          - 2
    #          - 3
    #
        gummei: 
          plmn_id:
            mcc: 460
            mnc: 99
          mme_gid: 1
          mme_code: 1

    #
    #  <TAI>
    #
    #  o Multiple TAI
    #    tai:
    #      - plmn_id:
    #          mcc: 001
    #          mnc: 01
    #        tac: [1, 2, 3]
    #    tai:
    #      - plmn_id:
    #          mcc: 002
    #          mnc: 02
    #        tac: 4
    #      - plmn_id:
    #          mcc: 003
    #          mnc: 03
    #        tac: 5
    #    tai:
    #      - plmn_id:
    #          mcc: 004
    #          mnc: 04
    #        tac: [6, 7]
    #      - plmn_id:
    #          mcc: 005
    #          mnc: 05
    #        tac: 8
    #      - plmn_id:
    #          mcc: 006
    #          mnc: 06
    #        tac: [9, 10]
    #
        tai:
          plmn_id:
            mcc: 460
            mnc: 99
          tac: 1

        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]

    #
    #  <Network Name>
    #    network_name:
    #        full: free5GC
    #        short: free
    #

        network_name:
            full: free5GC

    hss:
        freeDiameter: hss.conf

    pcrf:
        freeDiameter: pcrf.conf

    smf:
        freeDiameter: smf.conf

        pfcp:
          - addr: 192.168.2.4

        upf:
          - addr: 192.168.2.5

        http:
          addr: 192.168.2.4
          port: 8080

    #
    #  <UE Pool>
    #
    #  o IPv4 Pool
    #    $ sudo ip addr add 45.45.0.1/16 dev uptun
    #
    #    ue_pool:
    #      addr: 45.45.0.1/16
    #
    #  o IPv4/IPv6 Pool
    #    $ sudo ip addr add 45.45.0.1/16 dev uptun
    #    $ sudo ip addr add cafe:1::1/64 dev uptun
    #
    #    ue_pool:
    #      - addr: 45.45.0.1/16
    #      - addr: cafe:1::1/64
    #
    #
    #  o Specific APN(e.g 'volte') uses 45.46.0.1/16, cafe:2::1/64
    #    All other APNs use 45.45.0.1/16, cafe:1::1/64
    #    $ sudo ip addr add 45.45.0.1/16 dev uptun
    #    $ sudo ip addr add 45.46.0.1/16 dev uptun
    #    $ sudo ip addr add cafe:1::1/64 dev uptun
    #    $ sudo ip addr add cafe:2::1/64 dev uptun
    #
    #    ue_pool:
    #      - addr: 45.45.0.1/16
    #      - addr: cafe:1::1/64
    #      - addr: 45.46.0.1/16
    #        apn: volte
    #      - addr: cafe:2::1/64
    #        apn: volte
    #
    #  o Multiple Devices (default: uptun)
    #    $ sudo ip addr add 45.45.0.1/16 dev uptun
    #    $ sudo ip addr add cafe:1::1/64 dev uptun2
    #    $ sudo ip addr add 45.46.0.1/16 dev uptun3
    #    $ sudo ip addr add cafe:2::1/64 dev uptun3
    #
    #    ue_pool:
    #      - addr: 45.45.0.1/16
    #      - addr: cafe:1::1/64
    #        dev: uptun2
    #      - addr: 45.46.0.1/16
    #        apn: volte
    #        dev: uptun3
    #      - addr: cafe:2::1/64
    #        apn: volte
    #        dev: uptun3
    #
        ue_pool:
          - addr: 45.45.0.1/16

    #
    #  <Domain Name Server>
    #
    #  o Primary/Secondary can be configured. Others are ignored.
    #
        dns:
          - 8.8.8.8
          - 8.8.4.4

    upf:
        pfcp:
          addr:
            - 192.168.2.5

    #
    #  <GTP-U Server>>
    #
    #  o GTP-U Server(127.0.0.3:2152, [::1]:2152)
    #    gtpu:
    #      - addr: 127.0.0.3
    #      - addr: ::1
    #
    #  o Same configuration(127.0.0.3:2152, [::1]:2152) as below.
    #    gtpu:
    #      name: localhost
    #
        gtpu:
          - addr: 192.168.2.5

        ue_pool:
          - addr: 45.45.0.1/16

        dns:
          - 8.8.8.8
          - 8.8.4.4
kind: ConfigMap
metadata:
  name: free5gc-configmap

