apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-smf-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-smf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-smf
    spec:
      containers:      
      - name: myapp-container
        image: cewuandy/free5gc-base
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "/root/free5gc/free5gc-smfd"]
        volumeMounts:
        - name: free5gc-config
          mountPath: /root/free5gc/install/etc/free5gc/free5gc.conf
          subPath: free5gc.conf
        - name: free5gc-freediameter-config
          mountPath: /root/free5gc/install/etc/free5gc/freeDiameter/smf.conf
          subPath: smf.conf
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.168.2.4/24"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: free5gc-config
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5gc.conf
            path: free5gc.conf
      - name: free5gc-freediameter-config
        configMap:
          name: free5gc-freediameter-configmap
          items:
          - key: smf.conf
            path: smf.conf
