apiVersion: v1
data:
  amf.conf: |
    Identity = "amf.localdomain";
    
    Realm = "localdomain";
    
    No_SCTP;
    
    ListenOn = "192.168.2.2";

    TLS_Cred = "/root/free5gc/install/etc/free5gc/freeDiameter/amf.cert.pem", "/root/free5gc/install/etc/free5gc/freeDiameter/amf.key.pem";
    TLS_CA = "/root/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";

    LoadExtension = "dbg_msg_dumps.so" : "0x8888";
    LoadExtension = "dict_rfc5777.so";
    LoadExtension = "dict_mip6i.so";
    LoadExtension = "dict_nasreq.so";
    LoadExtension = "dict_nas_mipv6.so";
    LoadExtension = "dict_dcca.so";
    LoadExtension = "dict_dcca_3gpp.so";
    LoadExtension = "dict_s6a.so";
    ConnectPeer = "hss.localdomain" { ConnectTo = "192.168.2.3"; No_TLS; }; 
  smf.conf: |
    Identity = "smf.localdomain";
    
    Realm = "localdomain";
    
    No_SCTP;
    
    ListenOn = "192.168.2.4";

    TLS_Cred = "/root/free5gc/install/etc/free5gc/freeDiameter/smf.cert.pem", "/root/free5gc/install/etc/free5gc/freeDiameter/smf.key.pem";
    TLS_CA = "/root/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
    
    LoadExtension = "dbg_msg_dumps.so" : "0x8888";
    LoadExtension = "dict_rfc5777.so";
    LoadExtension = "dict_mip6i.so";
    LoadExtension = "dict_nasreq.so";
    LoadExtension = "dict_nas_mipv6.so";
    LoadExtension = "dict_dcca.so";
    LoadExtension = "dict_dcca_3gpp.so";
    
    ConnectPeer = "pcrf.localdomain" { ConnectTo = "192.168.2.6"; No_TLS; };
kind: ConfigMap
metadata:
  name: free5gc-freediameter-configmap
