apiVersion: v1
data:
  pcrf.conf: |
    Identity = "pcrf.localdomain";
    
    Realm = "localdomain";
    
    No_SCTP;
    
    ListenOn = "192.168.2.6";

    TLS_Cred = "/root/free5gc/install/etc/free5gc/freeDiameter/pcrf.cert.pem", "/root/free5gc/install/etc/free5gc/freeDiameter/pcrf.key.pem";
    TLS_CA = "/root/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
    
    LoadExtension = "dbg_msg_dumps.so" : "0x8888";
    LoadExtension = "dict_rfc5777.so";
    LoadExtension = "dict_mip6i.so";
    LoadExtension = "dict_nasreq.so";
    LoadExtension = "dict_nas_mipv6.so";
    LoadExtension = "dict_dcca.so";
    LoadExtension = "dict_dcca_3gpp.so";
    
    ConnectPeer = "smf.localdomain" { ConnectTo = "192.168.2.4"; No_TLS; };

  hss.conf: |
    Identity = "hss.localdomain";
    
    Realm = "localdomain";
    
    No_SCTP;
    
    ListenOn = "192.168.2.3";

    TLS_Cred = "/root/free5gc/install/etc/free5gc/freeDiameter/hss.cert.pem", "/root/free5gc/install/etc/free5gc/freeDiameter/hss.key.pem";
    TLS_CA = "/root/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
    
    LoadExtension = "dbg_msg_dumps.so" : "0x8888";
    LoadExtension = "dict_rfc5777.so";
    LoadExtension = "dict_mip6i.so";
    LoadExtension = "dict_nasreq.so";
    LoadExtension = "dict_nas_mipv6.so";
    LoadExtension = "dict_dcca.so";
    LoadExtension = "dict_dcca_3gpp.so";
    LoadExtension = "dict_s6a.so";
    
    ConnectPeer = "amf.localdomain" { ConnectTo = "192.168.2.2"; No_TLS; };

kind: ConfigMap
metadata:
  name: nextepc-freediameter-configmap
