apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nextepc-hss-deployment
spec:
  selector:
    matchLabels:
      app: nextepc-hss
  replicas: 1
  template:
    metadata:
      labels:
        app: nextepc-hss
    spec:
      containers:      
      - name: myapp-container
        image: cewuandy/free5gc-base
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "/root/free5gc/nextepc-hssd"]
        volumeMounts:
        - name: free5gc-config
          mountPath: /root/free5gc/install/etc/free5gc/free5gc.conf
          subPath: free5gc.conf
        - name: nextepc-config
          mountPath: /root/free5gc/install/etc/free5gc/hss.conf
          subPath: hss.conf
        - name: nextepc-freediameter-config
          mountPath: /root/free5gc/install/etc/free5gc/freeDiameter/hss.conf
          subPath: hss.conf
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.168.2.3/24"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: free5gc-config
        configMap:
          name: free5gc-configmap
          items:
          - key: free5gc.conf
            path: free5gc.conf
      - name: nextepc-config
        configMap:
          name: nextepc-configmap
          items: 
          - key: hss.conf
            path: hss.conf
      - name: nextepc-freediameter-config
        configMap:
          name: nextepc-freediameter-configmap
          items:
          - key: hss.conf
            path: hss.conf
